### ISSUE TITLE
在ui线程使用cachingSystem.addInCache这个会ANR吧

### ISSUE THREAD

**Issue by wangweiqi23** [lizubing1992/Smartcacheforretrofit2#1]
Runnable responseRunnable = new Runnable() {
  @Override
public void run() {
  if (response.isSuccessful()) {
     byte[] rawData = SmartUtils.responseToBytes(retrofit, response.body(),
     responseType(), annotations);
     cachingSystem.addInCache(response, rawData);
  }
  callback.onResponse(call, response);
  }
};
// Run it on the proper thread
callbackExecutor.execute(responseRunnable);

**Comment by lizubing1992** [comment]
如果是单独使用的，会导致ANR的，现在是在Runable里面使用，没ANR这个问题
